version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80" # Mapeia a porta 80 do contêiner para a porta 8000 do host
    volumes:
      - .:/var/www/html # Monta o diretório atual do host dentro do contêiner
